server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true

jwt.secret=aB3dE7fG9hJ2kL5mN8pQ1rS4tU7vW0xY3zA6bC9dE2fG5hI8jK1lM4nO7
jwt.expiration=86400000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.com.taskmanager=DEBUG

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-exception=false
server.error.include-stacktrace=on_param